# Generated by Django 5.2.5 on 2025-08-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='buteur',
            field=models.CharField(blank=True, default='', help_text='Nom du buteur principal', max_length=120),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('SUSPENDED', 'Suspended')], default='SCHEDULED', max_length=10),
        ),
    ]
