# Generated by Django 5.2.5 on 2025-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('matches', '0002_match_buteur_alter_match_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_club', models.F('away_club')), _negated=True), name='match_home_neq_away'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('round', 'home_club', 'away_club'), name='uniq_round_home_away_in_round'),
        ),
    ]
