# Generated by Django 5.2.5 on 2025-08-25 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_match_home_neq_away_and_more'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assist_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='goal',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='players.player'),
        ),
    ]
