# Generated by Django 5.2.5 on 2025-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_goal_assist_name_goal_assist_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['number', 'id']},
        ),
        migrations.AddField(
            model_name='round',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('HT', 'Half-time'), ('PAUSED', 'Paused'), ('FT', 'Full-time'), ('FINISHED', 'Finished'), ('SUSPENDED', 'Suspended'), ('POSTPONED', 'Postponed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=10),
        ),
    ]
