# Generated by Django 5.2.5 on 2025-09-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_staffmember'),
        ('matches', '0005_alter_round_options_round_number_alter_match_status'),
        ('players', '0002_alter_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=120)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=8)),
                ('is_starting', models.BooleanField(default=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
            ],
            options={
                'ordering': ['club_id', '-is_starting', 'number', 'player_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamInfoPerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(blank=True, max_length=20)),
                ('coach_name', models.CharField(blank=True, max_length=120)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_infos', to='matches.match')),
            ],
            options={
                'unique_together': {('match', 'club')},
            },
        ),
    ]
