# Generated by Django 5.2.5 on 2025-09-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_lineup_teaminfopermatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineup',
            options={'ordering': ['club_id', '-is_starting', 'number', 'id']},
        ),
        migrations.AlterModelOptions(
            name='teaminfopermatch',
            options={'verbose_name': 'Team info per match', 'verbose_name_plural': 'Team info per matches'},
        ),
        migrations.AlterField(
            model_name='lineup',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='photo',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('CB', 'Centre Back'), ('LB', 'Left Back'), ('DM', 'Defensive Mid'), ('CM', 'Centre Mid'), ('AM', 'Attacking Mid'), ('RW', 'Right Wing'), ('LW', 'Left Wing'), ('ST', 'Striker')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfopermatch',
            name='coach_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='teaminfopermatch',
            name='formation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
