# Generated by Django 5.2.5 on 2025-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_lineup_options_alter_teaminfopermatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='position',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('HT', 'Half-time'), ('PAUSED', 'Paused'), ('FT', 'Full-time'), ('FINISHED', 'Finished'), ('SUSPENDED', 'Suspended'), ('POSTPONED', 'Postponed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=12),
        ),
        migrations.AlterField(
            model_name='teaminfopermatch',
            name='coach_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
