# Generated by Django 5.2.5 on 2025-09-22 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_staffmember'),
        ('matches', '0008_goal_type_alter_lineup_number_and_more'),
        ('players', '0002_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='minutes_played',
            field=models.PositiveIntegerField(default=0, help_text='Minutes jouées (0 si non entré)'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Note de match (1.0 à 10.0). Laisser vide si le joueur n'a pas joué.", max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddIndex(
            model_name='lineup',
            index=models.Index(fields=['match', 'club'], name='matches_lin_match_i_e6d8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='lineup',
            index=models.Index(fields=['match', 'club', 'is_starting'], name='matches_lin_match_i_08e86b_idx'),
        ),
    ]
