# Generated by Django 5.2.5 on 2025-09-23 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_lineup_minutes_played_alter_lineup_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Note de match (1.0 à 10.0). Laisser vide si le joueur n'a pas joué.", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
