# Generated by Django 5.2.5 on 2025-10-13 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_lineup_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='minutes_played',
            field=models.PositiveIntegerField(default=0, help_text='Minutes jouées (optionnel, ignoré pour la note)'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Note de match (1.0 à 10.0). Laisser vide s'il n'y a pas de note.", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
