# Generated by Django 5.2.5 on 2025-10-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_lineup_minutes_played_alter_lineup_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='kickoff_1',
            field=models.DateTimeField(blank=True, help_text='Heure réelle du début de la 1ère mi-temps (UTC).', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='kickoff_2',
            field=models.DateTimeField(blank=True, help_text='Heure réelle du début de la 2ème mi-temps (UTC).', null=True),
        ),
    ]
