# Generated by Django 5.2.5 on 2025-11-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_logo_alter_staffmember_photo'),
        ('matches', '0012_match_kickoff_1_match_kickoff_2'),
        ('players', '0003_alter_player_last_name_alter_player_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineup',
            options={'ordering': ['match', 'club', '-is_starting', 'seq', 'number', 'id']},
        ),
        migrations.AddField(
            model_name='lineup',
            name='seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lineup',
            index=models.Index(fields=['match', 'club', 'seq'], name='matches_lin_match_i_472d57_idx'),
        ),
    ]
