version: "3.9"
services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: profootgn
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_NAME: profootgn
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DEBUG: "True"
      ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"

volumes:
  dbdata:
