# Generated by Django 5.2.5 on 2025-12-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adstat',
            index=models.Index(fields=['ad', 'event', 'created_at'], name='ads_adstat_ad_id_88aefc_idx'),
        ),
    ]
