# Generated by Django 4.2.27 on 2026-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adstat_ads_adstat_ad_id_88aefc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='club_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='competition_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='position',
            field=models.CharField(choices=[('top', 'Haut'), ('middle', 'Milieu'), ('bottom', 'Bas')], default='top', max_length=50),
        ),
    ]
