# Generated by Django 4.2.27 on 2026-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_ad_type_ad_club_id_ad_competition_id_ad_match_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/'),
        ),
    ]
