# Generated by Django 4.2.27 on 2026-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_image_alter_ad_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['page', 'position', 'active'], name='ads_ad_page_1e949a_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['competition_id'], name='ads_ad_competi_c5b62e_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['match_id'], name='ads_ad_match_i_40c1be_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['club_id'], name='ads_ad_club_id_a341e4_idx'),
        ),
    ]
