# Generated by Django 5.2.5 on 2025-09-03 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('PRESIDENT', 'Président'), ('COACH', 'Entraîneur principal'), ('ASSIST_COACH', 'Adjoint'), ('DIRECTOR', 'Directeur sportif'), ('TEAM_MANAGER', 'Team manager'), ('PHYSIO', 'Kinésithérapeute'), ('GK_COACH', 'Coach gardiens'), ('ANALYST', 'Analyste vidéo'), ('KIT_MANAGER', 'Intendant')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clubs.club')),
            ],
            options={
                'indexes': [models.Index(fields=['club', 'role', 'full_name'], name='clubs_staff_club_id_606c9f_idx')],
            },
        ),
    ]
