# Generated by Django 5.2.5 on 2025-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_staffmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='staff/'),
        ),
    ]
