# Generated by Django 4.2.27 on 2025-12-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('league', 'Championnat'), ('cup', 'Coupe'), ('supercup', 'Super Coupe'), ('friendly', 'Amical')], max_length=20)),
                ('category', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Féminin'), ('informel', 'Informel')], max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('country', models.CharField(default='Guinée', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
