# Generated by Django 4.2.27 on 2025-12-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_logo_alter_staffmember_photo'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='CompetitionClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_competitions', to='clubs.club')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_clubs', to='competitions.competition')),
            ],
            options={
                'verbose_name': 'Club engagé',
                'verbose_name_plural': 'Clubs engagés',
                'unique_together': {('competition', 'club')},
            },
        ),
    ]
