# Generated by Django 4.2.27 on 2025-12-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competition_slug_competitionclub'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('LIVE', 'En cours'), ('HT', 'Mi-temps'), ('FT', 'Terminé'), ('POSTPONED', 'Reporté'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=20)),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Match de compétition',
                'verbose_name_plural': 'Matchs de compétition',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Numéro de la journée (J1, J2...)')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Journée de compétition',
                'verbose_name_plural': 'Journées de compétition',
                'ordering': ['competition', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de l’équipe dans cette compétition', max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, max_length=500, null=True, upload_to='teams/')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('coach', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Équipe de compétition',
                'verbose_name_plural': 'Équipes de compétition',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='competitionclub',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='competitionclub',
            name='club',
        ),
        migrations.RemoveField(
            model_name='competitionclub',
            name='competition',
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['category', 'season'], name='competition_categor_06ca77_idx'),
        ),
        migrations.DeleteModel(
            name='CompetitionClub',
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionround',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='competitions.competitionteam'),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='competitions.competitionteam'),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.competitionround'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='competitionround',
            unique_together={('competition', 'number')},
        ),
        migrations.AddConstraint(
            model_name='competitionmatch',
            constraint=models.CheckConstraint(check=models.Q(('home_team', models.F('away_team')), _negated=True), name='competition_match_home_neq_away'),
        ),
        migrations.AddConstraint(
            model_name='competitionmatch',
            constraint=models.UniqueConstraint(fields=('competition', 'round', 'home_team', 'away_team'), name='uniq_competition_match_per_round'),
        ),
    ]
