# Generated by Django 4.2.27 on 2025-12-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competitionmatch_competitionround_competitionteam_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionround',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='competitionround',
            name='competition',
        ),
        migrations.AlterModelOptions(
            name='competitionmatch',
            options={'ordering': ['matchday', 'datetime'], 'verbose_name': 'Match de compétition', 'verbose_name_plural': 'Matchs de compétition'},
        ),
        migrations.RemoveConstraint(
            model_name='competitionmatch',
            name='uniq_competition_match_per_round',
        ),
        migrations.RemoveField(
            model_name='competitionmatch',
            name='round',
        ),
        migrations.RemoveField(
            model_name='competitionmatch',
            name='venue',
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='matchday',
            field=models.PositiveIntegerField(default=1, help_text='Journée (ex: 1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='CompetitionRound',
        ),
    ]
