# Generated by Django 4.2.27 on 2026-01-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_competitionround_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Nombre de points retirés (ex: -3) ou ajoutés (+1)')),
                ('reason', models.CharField(blank=True, help_text='Motif de la sanction', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='competitions.competitionteam')),
            ],
            options={
                'verbose_name': 'Pénalité de points',
                'verbose_name_plural': 'Pénalités de points',
                'ordering': ['-created_at'],
                'unique_together': {('competition', 'team', 'created_at')},
            },
        ),
    ]
