# Generated by Django 4.2.27 on 2026-01-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competitionpenalty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionpenalty',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='elapsed_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Temps écoulé cumulé en secondes (hors pause)'),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Heure réelle de démarrage du match', null=True),
        ),
    ]
