# Generated by Django 4.2.27 on 2026-02-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_competitionpenalty_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('GK', 'Gardien'), ('DEF', 'Défenseur'), ('MID', 'Milieu'), ('ATT', 'Attaquant')], max_length=10)),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='players/')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Joueur',
                'verbose_name_plural': 'Joueurs',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='competitionmatch',
            name='elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitionmatch',
            name='matchday',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='competitionmatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionpenalty',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='competitionpenalty',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='competitionteam',
            index=models.Index(fields=['competition', 'is_active'], name='competition_competi_28bba6_idx'),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='competitions.competitionteam'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['club', 'is_active'], name='competition_club_id_36b8b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('club', 'number')},
        ),
    ]
