# Generated by Django 4.2.27 on 2026-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_player_alter_competitionmatch_elapsed_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Taille en centimètres', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_club_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_club_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_club_3',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
