# Generated by Django 4.2.27 on 2026-02-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_player_height_player_previous_club_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='competition_logos/'),
        ),
    ]
