# Generated by Django 4.2.27 on 2026-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_player_assists_player_goals_player_matches_played_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionmatch',
            old_name='started_at',
            new_name='phase_start',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='competitionmatch',
            name='elapsed_seconds',
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='phase_offset',
            field=models.IntegerField(default=0),
        ),
    ]
