# Generated by Django 4.2.27 on 2026-03-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_rename_started_at_competitionmatch_phase_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmatch',
            name='phase_offset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CompetitionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='competitions.competitionstage')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competitions.competitionstage')),
            ],
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.competitiongroup'),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.competitionround'),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.competitionstage'),
        ),
    ]
