# Generated by Django 4.2.27 on 2026-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_alter_competitionmatch_phase_offset_competitionstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='reason',
            field=models.CharField(choices=[('foul', 'Faute'), ('dissent', 'Contestation'), ('simulation', 'Simulation'), ('other', 'Autre')], default='foul', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('penalty', 'Pénalty'), ('freekick', 'Coup franc'), ('own_goal', 'CSC')], default='normal', max_length=20),
        ),
    ]
