# Generated by Django 4.2.27 on 2026-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_card_reason_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='reason',
            field=models.CharField(choices=[('foul', 'Faute'), ('protest', 'Contestations'), ('simulation', 'Simulation'), ('time_wasting', 'Perte de temps'), ('violence', 'Violence'), ('other', 'Autre')], default='foul', max_length=20),
        ),
    ]
