# Generated by Django 4.2.27 on 2026-05-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_alter_card_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=False)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_goalkeeper', models.BooleanField(default=False)),
                ('minute_in', models.PositiveIntegerField(blank=True, null=True)),
                ('minute_out', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='competitions.competitionmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionteam')),
            ],
            options={
                'ordering': ['team', '-is_starter'],
            },
        ),
    ]
