# Generated by Django 4.2.27 on 2026-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_matchlineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Gardien'), ('LB', 'Latéral gauche'), ('CB', 'Défenseur central'), ('RB', 'Latéral droit'), ('DM', 'Milieu défensif'), ('CM', 'Milieu central'), ('AM', 'Milieu offensif'), ('LW', 'Ailier gauche'), ('RW', 'Ailier droit'), ('ST', 'Attaquant')], max_length=10, null=True),
        ),
    ]
