# Generated by Django 4.2.27 on 2026-05-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_matchlineup_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='is_player_of_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
