# Generated by Django 4.2.27 on 2026-05-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_matchlineup_is_player_of_match_matchlineup_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='competitions.competitionmatch')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_in', to='competitions.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_out', to='competitions.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionteam')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
    ]
