# Generated by Django 4.2.27 on 2026-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_matchsubstitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchlineup',
            name='is_player_of_match',
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='man_of_match',
            field=models.BooleanField(default=False),
        ),
    ]
