# Generated by Django 4.2.27 on 2026-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_remove_matchlineup_is_player_of_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionpenalty',
            name='away_formation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='competitionpenalty',
            name='home_formation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
