# Generated by Django 4.2.27 on 2026-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_competitionpenalty_away_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='x',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='y',
            field=models.IntegerField(default=50),
        ),
    ]
