# Generated by Django 4.2.27 on 2026-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_matchlineup_x_matchlineup_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmatch',
            name='away_formation',
            field=models.CharField(default='4-3-3', max_length=20),
        ),
        migrations.AddField(
            model_name='competitionmatch',
            name='home_formation',
            field=models.CharField(default='4-3-3', max_length=20),
        ),
    ]
