# Generated by Django 5.2.5 on 2025-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_logo_alter_staffmember_photo'),
        ('players', '0002_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='players/'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['club', 'last_name', 'first_name'], name='players_pla_club_id_59c843_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position'], name='players_pla_positio_2502c1_idx'),
        ),
    ]
